---
# tasks file for vector-role
    - name: Create directory Vect
      become_user: root
      become: true
      become_method: su
      become_exe: sudo su
      ansible.builtin.file: path=/vect state=directory
    - name: Download Vector
      become_user: root
      become: true
      become_method: su
      become_exe: sudo su
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.0/vector-0.21.0-1.x86_64.rpm"
        dest: "/vect"
        mode: 0664
    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name: "/vect/vector-0.21.0-1.x86_64.rpm"
